site_name: Cornmaze
theme:
  name: readthedocs
repo_url: https://github.com/TurnipXenon/cornmaze
nav:
  - Home: index.md
  - Onboarding: onboarding.md
  - Interacting with cornmaze: interacting_with_cornmaze.md
  - Private workflow: private_workflow.md
  - Code standards: code_standards.md