site_name: Turnip
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Onboarding: onboarding.md
  - Interacting with cornmaze: interacting_with_cornmaze.md
  - Private workflow: private_workflow.md
  - Code standards: code_standards.md